### PR TITLE
Add changelog for 1.3.4

### PR DESCRIPTION
**Pull request by ruuda**
Let’s make a new release with the few small bugfixes for the maintainer.

### CODE REVIEW

**Comment by ruuda** [comment]
@enriquefynn, I now also included @kkonevets changes to handle the error that the maintainer is running into, let’s make a new release and deploy this today, can you take a look?

**Review by enriquefynn — APPROVED** [review]
LGTM, but we need to do another version to include changes from #583 or we could try to include them here

**Comment by ruuda** [comment]
> we need to do another version to include changes from https://github.com/ChorusOne/solido/pull/583

Ah yes, good point. I will cherry-pick it onto `current` and include it in the changelog.

**Comment by kkonevets** [comment]
@ruuda [this commit](https://github.com/ChorusOne/solido/pull/583) is not valid, don't cherry pick it please

**Comment by ruuda** [comment]
Okay, I reverted back to `e83ce9bf`, the deactivation is not going to happen in the very near future either way, let’s get the current fixes deployed before the end of the epoch.

**Pull request merged**
